name: Publish

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get release info
        id: query-release-info
        uses: release-flow/keep-a-changelog-action@v2
        with:
          command: query
          version: latest

      - name: Publish to Github releases
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.query-release-info.outputs.release-notes }}
          # prerelease: true
          # files: '*.vsix'
